### ISSUE TITLE
Install:  No module named 'pyTuttle'

### ISSUE THREAD

**Issue by raphaelbastide** [buttleofx/ButtleOFX#102]
I am trying to install the current GitHub version.
The install process outputs this message after the `python3 buttleApp.py` command:

```
No module named 'pyTuttle'
```

**Comment by JamesWrigley** [comment]
I believe this is the same issue as #55.

**Comment by fabiencastan** [comment]
If you use linux 64 bits, you can download the binaries:
https://buttleofx.wordpress.com/downloads

If you want to use the git repository: just replace the directory ButtleOFX inside with the github clone.

If you use another system, you will have to install python3, pyqt5 and TuttleOFX with its dependencies. So it could be a huge work.

**Comment by raphaelbastide** [comment]
The binaries resolves the issue thank you.
