### ISSUE TITLE
Nothing in the viewer

### ISSUE THREAD

**Issue by raphaelbastide** [buttleofx/ButtleOFX#103]
Not sure it is a normal behavior, but nothing is displayed in the viewer, at any time.
In the following example, a jpg node is selected, I guess it should appear in the viewer right?
I am on Debian testing and downloaded the ButtleOFX alpha version.

![](http://f.cl.ly/items/3D1c1Q2l2B173h2X2x1L/gnome-shell-cloudapp-Q04WGX.png)

**Comment by eprana** [comment]
You have to drag and drop the mosquito to the node you want to see in the viewer. 
The node displayed contains a crushed mosquito !

**Comment by raphaelbastide** [comment]
Ok I get it now!
Let me suggest to question this behavior.
Maybe add a info box when user click or rollover on the mosquito. “Drag the mosquito on the node you want to preview”.
Maybe an alternative -more user friendly- action could be nice as well: for example click on the node I want to preview then click on the mosquito.
In my opinion, this mosquito dragging is really fun makes sense when you learn how to use it but not evident in a first place. It appears to be like an Easter egg, but preview action is one of the first action you want to do to make the program “prove it works” few seconds after a program execution. I think it is actually too important for not being evident. What are your thoughts about that?

**Comment by fabiencastan** [comment]
Selecting an image file in the browser should display the image in the viewer directly.
In the graph editor use middle-click on a node to display it in the viewer. The mosquito is only a way to make it understandable for the first time... but I just see that the tooltip on it is missing...

The left click is held for handling nodes (selection, move). Double left click is already used to open the parameters. And we would like to keep one-click to display the image.

The middle click is also used to move the graph.

**Comment by raphaelbastide** [comment]
Middle-click to preview is perfect!
Thank you.
