### ISSUE TITLE
browser: completion

### ISSUE THREAD

**Issue by fabiencastan** [buttleofx/ButtleOFX#136]
When there is only one solution, write the possible value in gray.

**/plop/pl**ip

**Comment by aoblet** [comment]
Feature ok.

**Comment by fabiencastan** [comment]
bug: gray completion stay there when we enter in the folder...

**Comment by fabiencastan** [comment]
bug: completion show all filenames than contains the intput text instead of showing filenames starting with the input text.

**Comment by fabiencastan** [comment]
Add "right arrow" shortcut to validate the proposed value.

**Comment by aoblet** [comment]
Possible to validate value by Tab(otherwise). It was wanted to show all filenames that contains the input. Is it undesired?
