### ISSUE TITLE
closing the application

### ISSUE THREAD

**Issue by fabiencastan** [buttleofx/ButtleOFX#137]
Process is still running.

**Comment by JamesWrigley** [comment]
Can't reproduce this on Fedora 21, when I close ButtleOFX I can see the process quit as well.

**Comment by fabiencastan** [comment]
I missed to precise that's a bug introduced recently with the "browser_v2", which is not yet merged in the "develop" branch.

**Comment by fabiencastan** [comment]
I missed to precise that's a bug introduced recently with the "browser_v2", which is not yet merged in the "develop" branch.

**Comment by fabiencastan** [comment]
I missed to precise that's a bug introduced recently with the "browser_v2", which is not yet merged in the "develop" branch.

**Comment by JamesWrigley** [comment]
Ah I see, sorry.

**Comment by aoblet** [comment]
Fixed
