### ISSUE TITLE
Tuttle error: on file without extension

### ISSUE THREAD

**Issue by aoblet** [buttleofx/ButtleOFX#148]
/home/fab/dev/TuttleOFX/libraries/tuttle/src/tuttle/host/io.cpp(92): Throw in function std::string tuttle::host::io::getFileExtension(const string&)
Dynamic exception type: boost::exception_detail::clone_impltuttle::exception::File
kOfxStatFailed[tuttle::exception::tag_devMessage_] = Filename has no extension "final".
[tuttle::exception::tag_userMessage_] = Filename has no extension "final".
[tuttle::exception::tag_backtraceMessage_] = 
[boost::errinfo_file_name__] = final

stop pysequenceParser::browse() process
See it with #139, or correct it with tuttle cpp or both?

**Comment by cchampet** [comment]
The problem is not in sequenceParser, which supports filename with no extension.
The problem is in tuttle: https://github.com/tuttleofx/TuttleOFX/blob/buttle3_upSequenceParserRemoveSam/libraries/tuttle/src/tuttle/host/io.cpp#L90

Don't you want to catch an exception when try to create a thumbnail from a file with no extension ?

**Comment by fabiencastan** [comment]
@aoblet There is no link with the sequenceParser.
It's during the thumbnail creation:
https://github.com/buttleofx/ButtleOFX/blob/f62bf047d2e57868ea10e5532f022cbda0ce5825/buttleofx/main.py#L197

But it's just a warning, there should be no problem.

**Comment by aoblet** [comment]
Actually it was crashing into browserItem by: bool(tuttle.getReaders) with a file without extension. I handled it. It's okay.

**Comment by fabiencastan** [comment]
crash != exception

**Comment by aoblet** [comment]
Yes sorry. I didn't catch the exception before.
