### ISSUE TITLE
What distro

### ISSUE THREAD

**Issue by xixoxuxa** [buttleofx/ButtleOFX#169]
What GNU/Linux distro does ButtleOFX run on for sure? I tried MInt 17 and it does not work...

**Comment by fabiencastan** [comment]
All devs are working on Ubuntu 14 and I also tested it on OpenSuse 12.1.
We will provide new binaries with the new code in 2 months.

**Comment by xixoxuxa** [comment]
Thank you very much for your precious reply. I will try the distros you mentioned.

**Comment by fabiencastan** [comment]
Just to be clear the current binary is an alpha version, which gives a good idea of the project but there is still some simple troubles that makes it not yet usable.
But we are really interested to get your feedback, your suggestions and the key features you are interested in.
Best regards

**Comment by xixoxuxa** [comment]
Yes, I know this is na alpha version so I expected some problems, hoped that I could at least launch the app. But, since, some people managed to test the program I thought there must be a distro it works on. I hope I will launch the app 'cause it looks promissing.
kind regards

**Comment by JamesWrigley** [comment]
I've used it on Fedora 21 and 20, works fine.
