### ISSUE TITLE
IsSecret property on parameters

### ISSUE THREAD

**Issue by fabiencastan** [buttleofx/ButtleOFX#23]
This property indicates if the parameter should be shown to the user.

**Comment by cchampet** [comment]
This property is constant for a parameter, or it can change (for example when we choose a particular value for a list, the parameter become secret) ?

**Comment by fabiencastan** [comment]
This property is not constant.
You often get a choice parameter "mode" that enable/hide other params.
You often get a choice parameter "preset" that modify other params values.
