### ISSUE TITLE
Connection output to input clip

### ISSUE THREAD

**Issue by fabiencastan** [buttleofx/ButtleOFX#27]
Instead of connecting an input on an output clip, I have tried to do the opposite:
Connect an output on an input... and it crashes.

**Comment by agreffard** [comment]
Yes, I noticed the bug too. It appears since the drag & drop, will be fixed soon !

**Comment by fabiencastan** [comment]
Ok.
Seems to have troubles with multiple inputs too (eg. Merge node).
