### ISSUE TITLE
Graph: qml binding loop

### ISSUE THREAD

**Issue by fabiencastan** [buttleofx/ButtleOFX#28]
ButtleOFX/buttleofx/gui/graph/qml/Graph.qml:60:17: QML Node: Binding loop detected for property "x"
ButtleOFX/buttleofx/gui/graph/qml/Graph.qml:60:17: QML Node: Binding loop detected for property "y"

**Comment by agreffard** [comment]
The binding loop appears after a zoom in the graph.
