### ISSUE TITLE
How to process images sequences ?

### ISSUE THREAD

**Issue by mfe** [buttleofx/ButtleOFX#51]
I tried to use # and @ paddings and to drag and drop some images from a sequence with no success.

**Comment by agreffard** [comment]
This is not yet implemented :)
The video/sequence management is very basic for the moment !

**Comment by fabiencastan** [comment]
Nothing to implement for that.
Seems to be a bug of the string param item, which refuses to change the value even on a simple image.
There is also an encoding problem, no accent supported in the path.
